### ISSUE TITLE
[aws_auto_checkin_app] botocore.exceptions.NoCredentialsError: Unable to locate credentials

### ISSUE THREAD

**Issue by nakane11** [nakane11/jsk_recognition#4]
### Error when the original node starts
```
[INFO] [1658570642.881295, 1497924865.514607]: Initiate User Auth for k-okada@jsk.t.u-tokyo.ac.jp
Traceback (most recent call last):
  File "/home/nakane/ros/jsk_recognition_ws/src/jsk_recognition/jsk_perception/node_scripts/aws_auto_checkin_app.py", line 165, in <module>
    auto = AutoCheckIn()
  File "/home/nakane/ros/jsk_recognition_ws/src/jsk_recognition/jsk_perception/node_scripts/aws_auto_checkin_app.py", line 67, in __init__
    self.id_token = self._get_id_token_by_cognito(env['UserName'], env['UserPassword'])
  File "/home/nakane/ros/jsk_recognition_ws/src/jsk_recognition/jsk_perception/node_scripts/aws_auto_checkin_app.py", line 37, in _get_id_token_by_cognito
    'PASSWORD': password
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 622, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 641, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/lib/python2.7/dist-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/lib/python2.7/dist-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/lib/python2.7/dist-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/usr/lib/python2.7/dist-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/lib/python2.7/dist-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/lib/python2.7/dist-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python2.7/dist-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/lib/python2.7/dist-packages/botocore/signers.py", line 160, in sign
    auth.add_auth(request)
  File "/usr/lib/python2.7/dist-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```
### [ExternalImageId](https://docs.aws.amazon.com/rekognition/latest/APIReference/API_Face.html#rekognition-Type-Face-ExternalImageId)  
Identifier that you assign to all the faces in the input image.

### Output after changed  
```
[INFO] [1658570563.934252, 1497924866.966674]: {u'SearchedFaceBoundingBox': {u'Width': 0.7391356229782104, u'Top': 0.16384845972061157, u'Left': 0.08479681611061096, u'Height': 0.8056470155715942}, u'SearchedFaceConfidence': 95.77082061767578, u'FaceMatches': [{u'Face': {u'BoundingBox': {u'Width': 0.452659010887146, u'Top': 0.2265550047159195, u'Left': 0.28277599811553955, u'Height': 0.43887999653816223}, u'FaceId': u'8980685b-9502-43ae-a0c2-74f8efb27853', u'Confidence': 99.99829864501953, u'ImageId': u'd52d064c-7e3b-3ca3-8455-f675b6651cc6'}, u'Similarity': 98.80288696289062}], u'FaceModelVersion': u'5.0', 'ResponseMetadata': {'RetryAttempts': 0, 'HTTPStatusCode': 200, 'RequestId': '03678d3e-9fa6-4dcc-93c2-fe9b887d94fa', 'HTTPHeaders': {'x-amzn-requestid': '03678d3e-9fa6-4dcc-93c2-fe9b887d94fa', 'date': 'Sat, 23 Jul 2022 10:02:43 GMT', 'content-length': '545', 'content-type': 'application/x-amz-json-1.1'}}}
[INFO] [1658570563.935366, 1497924866.966674]: FaceId: 8980685b-9502-43ae-a0c2-74f8efb27853
 Similarity: 98.8028869629
```

**Comment by nakane11** [comment]
collection_idを調べた方法　　
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rekognition.html#Rekognition.Client.list_collections
`botocore.client.Rekognition.list_collections(MaxResults=max_results)`

```
In [11]: client = boto3.client('rekognition', aws_access_key_id=***********, aws_secret_access_key=************
    ...: ', region_name="us-west-2")

In [12]: client
Out[12]: <botocore.client.Rekognition at 0x7fb090abc510>

In [13]: client.list_collections(MaxResults=5)
Out[13]: 
{u'CollectionIds': [u'auto-check-in-app-face-collection'],
 u'FaceModelVersions': [u'5.0'],
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '83',
   'content-type': 'application/x-amz-json-1.1',
   'date': 'Sat, 23 Jul 2022 08:23:06 GMT',
   'x-amzn-requestid': '***********************'},
  'HTTPStatusCode': 200,
  'RequestId': '*********************',
  'RetryAttempts': 0}}
```

**Comment by nakane11** [comment]
```
In [17]: client.describe_collection(CollectionId='auto-check-in-app-face-collect
    ...: ion')
```

`FaceModelVersion': u'5.0'`

モデルのバージョン
https://docs.aws.amazon.com/rekognition/latest/dg/face-detection-model.html

**Comment by nakane11** [comment]
既存のDunamoDB tableの名前を調べる方法　　
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.list_tables
```
In [4]: dynamodb_client=boto3.client(
   ...:     'dynamodb',
   ...:     aws_access_key_id='*********************',
   ...:     aws_secret_access_key='*********************',
   ...:     region_name='*********')

In [5]: dynamodb_client
Out[5]: <botocore.client.DynamoDB at 0x7f9d955f9ed0>

In [6]: dynamodb_client.list_tables()
Out[6]: 
{'ResponseMetadata': {'HTTPHeaders': {'connection': 'keep-alive',
   'content-length': '63',
   'content-type': 'application/x-amz-json-1.0',
   'date': 'Sat, 23 Jul 2022 23:10:40 GMT',
   'server': 'Server',
   'x-amz-crc32': '*********************',
   'x-amzn-requestid': '*********************'},
  'HTTPStatusCode': 200,
  'RequestId': '*********************',
  'RetryAttempts': 0},
 u'TableNames': [u'*********************']}
```
